name: "Secure Data Share Request (Identified → De-Identified Server)"
description: "Request secure share of data from identified server to de-identified snowflake server"
title: "[Secure Data Share] Share multiple tables from id-snowflake to deid-snowflake"
labels: ["snowshare", "data-deid", "review-needed"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Secure Data Transfer Request  
        This form is for requesting secure share de-identified tables/views from a **identified** to a **de-identified** snowflake server.  
        Please complete all required fields to ensure regulatory and security compliance.
  
  - type: input
    id: requester
    attributes:
      label: "Requester Name"
      placeholder: "Your full name"
    validations:
      required: true
  
  - type: input
    id: requester_email
    attributes:
      label: "Requester Email"
      placeholder: "email@example.edu"
    validations:
      required: true
  
  - type: input
    id: project_info
    attributes:
      label: "Project Title"
      placeholder: "Provide name of the project, which should already be approved to operate"
    validations:
      required: true
  
  - type: input
    id: source_database
    attributes:
      label: "Source Database Name"
      placeholder: "e.g., GROUSE_ANALYTICS_DB"
    validations:
      required: true

  - type: input
    id: source_schema
    attributes:
      label: "Source Schema Name(s)"
      placeholder: "e.g., SX_ALS_GPC"
    validations:
      required: true

  - type: input
    id: target_database
    attributes:
      label: "Target Database Name"
      placeholder: "e.g., GROUSE_DEID_ANALYTICS_DB_DROCXXX"
    validations:
      required: true

  - type: input
    id: target_schema
    attributes:
      label: "Target Schema Name"
      placeholder: "Specify if schema should retain name or be renamed. For renaming, specify as source_schema -> target_schema"
    validations:
      required: true

  - type: textarea
    id: deidentification_steps
    attributes:
      label: "De-identification Steps Applied (or Requested)"
      placeholder: "e.g., all 18 HIPAA identifiers are removed with dates converted to days since an index_date"
